RTI-1118 Fixed highlight opacity applied twice
ag-grid/ag-grid pull request #5740
Opened 2022-11-01 17:31 UTC by alexanderby

2022-11-01 17:37 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
> -        this.seriesGroup.opacity = this.getOpacity();
Opacity needs to be applied at the group(s) that map to layers so that opacity is applied during layer composition rather than during canvas rendering - is the opacity being applied elsewhere?

2022-11-01 17:42 UTC, alexanderby commented on charts-packages/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
> -        this.seriesGroup.opacity = this.getOpacity();
https://github.com/ag-grid/ag-grid/blob/5376db6f0a163ace3843cb9d49df2047d2c969ae/charts-packages/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts#L346

2022-11-02 07:46 UTC, alantreadway requested changes
Let's discuss offline.

2022-11-02 09:59 UTC, alantreadway approved these changes
LGTM, this may still have performance issues, but they are pre-existing.

2022-11-02 10:00 UTC, merged