AG-9871 Added check for disabled grid selection checkbox
ag-grid/ag-grid pull request #7327
Opened 2023-12-07 11:58 UTC by salmenus

2023-12-07 13:06 UTC, StephenCooper commented on grid-community-modules/core/src/ts/rendering/cell/cellKeyboardListenerFeature.ts
> +        if (!this.rowCtrl.hasDisabledRowSelectionCheckbox() && !this.cellCtrl.isEditing() && gridOptionsService.isRowSelection()) {
I would put this as the last condition as it is the most expensive to calculate. We would want to avoid running this seeing as it loops through every column.

2023-12-07 13:08 UTC, StephenCooper commented on grid-community-modules/core/src/ts/rendering/row/rowCtrl.ts
> +        return typeof checkboxSelection === 'function' && !checkboxSelection(params);
Isn't the check for if its a function redundant given the find above?

2023-12-07 13:36 UTC, salmenus commented on grid-community-modules/core/src/ts/rendering/row/rowCtrl.ts
> +        return typeof checkboxSelection === 'function' && !checkboxSelection(params);
added for Typescript, to avoid type casting.
i can do `(checkboxSelection as CheckboxSelectionCallbackParams)(params)` if you prefer that ?

2023-12-07 13:43 UTC, salmenus commented on grid-community-modules/core/src/ts/rendering/row/rowCtrl.ts
> +        return typeof checkboxSelection === 'function' && !checkboxSelection(params);
sure. we can cast to `CheckboxSelectionCallback` - done

2023-12-07 13:44 UTC, salmenus commented on grid-community-modules/core/src/ts/rendering/cell/cellKeyboardListenerFeature.ts
> +        if (!this.rowCtrl.hasDisabledRowSelectionCheckbox() && !this.cellCtrl.isEditing() && gridOptionsService.isRowSelection()) {
good call. done

2023-12-20 21:50 UTC, AndrewGlazier requested changes
I think we need to consider more than what's being done here.

For example `detailNodes` historically haven't been selectable it seems, which was done by adding `selectable = false` this change means we can now select detail nodes via API, this seems like it'd be an unintended side effect possibly.

When doing transactions (CSRM and SSRM), it seems when we do an update, we deselect selected nodes which aren't selectable any more, this seems like it won't work with this new behaviour, as selectable and selected are less coupled, so this needs considered

It also looks like changes are needed in the serverSideSelectionService too

2023-12-20 21:50 UTC, AndrewGlazier commented on grid-community-modules/core/src/ts/selectionService.ts
> +            const skipThisNode = !isApiSelection && groupSelectsFiltered && node.group;
I'm struggling to work out why this needs changed - the behaviour we want is that api ignores `selectable` - but this seems to leave the scope of that?

2024-01-04 10:07 UTC, salmenus commented on grid-community-modules/core/src/ts/selectionService.ts
> +            const skipThisNode = !isApiSelection && groupSelectsFiltered && node.group;
Logic updated

2024-01-04 10:45 UTC, salmenus commented on grid-community-modules/core/src/ts/entities/rowNode.ts
> +        if (this.detail || !changeSelectionAllowed || selectionNotChanged) { return false; }
When `this.detail` is set, `this.selectable` will be false ..

But since we want to override `this.selectable` when the call is made via `rowNode.setSelected(true)`, we will need to add a second check to exclude detail nodes.

2024-01-08 10:40 UTC, closed without merging